version: "4.22.1"
services:
  db:
    image: postgres
    container_name: local_pgdb
    restart: always
    ports:
      - "54320:5432"
    environment:
        POSTGRES_USER: user
        POSTGRES_PASSWORD: admin
        POSTGRES_DB: postgres

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin4_container
    restart: always
    ports:
      - "5050:80"
    environment:
        PGADMIN_DEFAULT_EMAIL: a@a.pl
        PGADMIN_DEFAULT_PASSWORD: admin
